import { useState, useCallback, useEffect, useRef } from 'react'
import {
  X,
  Wrench,
  GitCommit,
  RefreshCw,
  Check,
  ClipboardCopy,
  Play,
  ShieldAlert,
  AlertCircle,
  Loader2,
  Eye,
  ExternalLink,
} from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { cn } from '../../../lib/utils'
import { useSocket } from '../../../providers/socket-provider'
import { useCommandState } from '../../../providers/command-state-provider'
import { useIdeConfig } from '../../../hooks/use-ide-config'
import { useFixFinding } from '../hooks/use-fix-finding'
import type { Finding } from '../../../lib/api-types'

type Tab = 'agent' | 'commit' | 'review'

type Props = {
  findings: Finding[]
  sessionId: string
  roundNumber: number
  initialPerNotes?: Record<number, string>
  onClose: () => void
}

const SEVERITY_CLS: Record<string, string> = {
  critical: 'bg-red-500/15 text-red-700 dark:text-red-400',
  high: 'bg-orange-500/15 text-orange-700 dark:text-orange-400',
  medium: 'bg-amber-500/15 text-amber-700 dark:text-amber-400',
  low: 'bg-blue-500/15 text-blue-700 dark:text-blue-400',
  info: 'bg-zinc-500/15 text-zinc-600 dark:text-zinc-400',
}

type RemotePrContext = {
  owner: string
  repo: string
  headRef: string
  isCollaborator: boolean
  prNumber?: number
  prUrl?: string
}

function buildBatchPrompt(
  findings: Finding[],
  roundNumber: number,
  perNotes: Record<number, string>,
  globalNotes: string,
  remotePr?: RemotePrContext,
): string {
  const findingBlocks = findings
    .map((f, i) => {
      const location = f.file_path
        ? `File: ${f.file_path}${f.line_start != null ? `:${f.line_start}` : ''}`
        : null
      const note = perNotes[f.id]?.trim()
      // ReviewHeading is the exact heading line from the original PR review comment
      // (e.g. "### 🚫 1. Title" or "### 1. Title" or "- \"suggestion text\"")
      // The agent uses this verbatim when posting the post-fix PR comment.
      const reviewHeading = f.summary?.split('\n')[0]?.trim() ?? f.title
      return [
        `--- Finding ${i + 1} of ${findings.length} ---`,
        `Severity: ${f.severity.toUpperCase()}`,
        `Title: ${f.title}`,
        `ReviewHeading: ${reviewHeading}`,
        location,
        f.summary ? `Description: ${f.summary}` : null,
        note ? `Author note: ${note}` : null,
      ]
        .filter(Boolean)
        .join('\n')
    })
    .join('\n\n')

  const globalSection = globalNotes.trim()
    ? `\nGlobal context (applies to all findings):\n${globalNotes.trim()}\n`
    : ''

  let remoteSection = ''
  if (remotePr) {
    if (remotePr.isCollaborator) {
      remoteSection = `\nREMOTE PR MODE (collaborator — you have push access):
- Fetch each file: gh api "repos/${remotePr.owner}/${remotePr.repo}/contents/{path}?ref=${remotePr.headRef}" | python3 -c "import sys,json,base64; print(base64.b64decode(json.load(sys.stdin)['content']).decode())"
- Get file SHA: gh api "repos/${remotePr.owner}/${remotePr.repo}/contents/{path}?ref=${remotePr.headRef}" --jq '.sha'
- Push fix: gh api "repos/${remotePr.owner}/${remotePr.repo}/contents/{path}" --method PUT --field message="fix: {description}" --field content="$(base64 -w0 {local_copy})" --field sha="{file_sha}" --field branch="${remotePr.headRef}"
- Target branch: ${remotePr.headRef} — do NOT push to main
- Do NOT run local git commands\n`
    } else {
      remoteSection = `\nREMOTE PR MODE (read-only — you do NOT have push access to ${remotePr.owner}/${remotePr.repo}):
- Fetch each file: gh api "repos/${remotePr.owner}/${remotePr.repo}/contents/{path}?ref=${remotePr.headRef}" | python3 -c "import sys,json,base64; print(base64.b64decode(json.load(sys.stdin)['content']).decode())"
- After making the fix locally, produce the unified diff and post it as a PR comment:
  gh pr comment {prNumber} --repo ${remotePr.owner}/${remotePr.repo} --body "## Suggested fix\\n\`\`\`diff\\n{unified_diff}\\n\`\`\`\\n_Generated by Author Agent — apply with \`git apply\`_"
- Do NOT attempt to push or commit — you have no write access
- Do NOT run local git commands\n`
    }
  }

  // Commit section — agent should not commit; Tab 2 (Commit & Push) handles this so there's no conflict
  const commitSection = ''

  // Post-fix comment section — only for remote collaborator sessions (where the agent already pushed)
  const canPostFix = remotePr?.isCollaborator === true
  const ghCommentTarget = remotePr?.prNumber != null
    ? `${remotePr.prNumber} --repo ${remotePr.owner}/${remotePr.repo}`
    : '$(gh pr view --json number --jq .number 2>/dev/null)'

  const postFixSection = canPostFix ? `

POST-FIX PR COMMENTS:
After all code changes are complete, post one GitHub PR comment per successfully-fixed finding so the reviewer can match each fix to the original issue they raised.

For each finding you fixed (in order, skip any you could not fix or was already resolved):
1. Write the comment body to a temp file — use the EXACT ReviewHeading from the finding block above as the first line, followed by a blank line and 1-2 sentences describing exactly what was changed:
   printf '%s\\n\\n%s' "{ReviewHeading}" "**Fixed**: {what file/lines changed and what the fix does}" > /tmp/ocr-fix-{N}.md
2. Post it:
   gh pr comment ${ghCommentTarget} --body-file /tmp/ocr-fix-{N}.md

The ReviewHeading must be copied verbatim — do NOT rephrase or reformat it. This is how the reviewer matches your comment to the original issue.
If gh pr view returns no PR (exit non-zero), skip the comment step entirely.` : ''

  return `You are an author fixing ${findings.length} code review finding${findings.length === 1 ? '' : 's'} from Round ${roundNumber} in a single pass.
${remoteSection}
${findingBlocks}
${globalSection}
INSTRUCTIONS:
1. Fix each finding with minimal, targeted changes
2. Address them in the order listed — skip any already resolved
3. Do not refactor surrounding code or change unrelated logic
4. Do NOT add comments explaining the changes
5. Report which files you changed and which findings each change addresses${postFixSection}${commitSection}`.trim()
}

function DiffView({ diff }: { diff: string }) {
  return (
    <div className="font-mono text-[11px] leading-relaxed">
      {diff.split('\n').map((line, i) => {
        let bg = ''
        let text = 'text-zinc-500 dark:text-zinc-400'
        if (line.startsWith('+++') || line.startsWith('---')) {
          text = 'text-zinc-700 dark:text-zinc-300 font-semibold'
        } else if (line.startsWith('diff ') || line.startsWith('index ')) {
          text = 'text-zinc-500 dark:text-zinc-500'
        } else if (line.startsWith('@@')) {
          bg = 'bg-blue-500/10'
          text = 'text-blue-700 dark:text-blue-400'
        } else if (line.startsWith('+')) {
          bg = 'bg-emerald-500/10'
          text = 'text-emerald-800 dark:text-emerald-300'
        } else if (line.startsWith('-')) {
          bg = 'bg-red-500/10'
          text = 'text-red-800 dark:text-red-400'
        }
        return (
          <div key={i} className={cn('px-3 py-px whitespace-pre', bg, text)}>
            {line || ' '}
          </div>
        )
      })}
    </div>
  )
}

export function BatchFixDialog({ findings, sessionId, roundNumber, initialPerNotes, onClose }: Props) {
  const [tab, setTab] = useState<Tab>('agent')
  const [globalNotes, setGlobalNotes] = useState('')
  const [perNotes, setPerNotes] = useState<Record<number, string>>(initialPerNotes ?? {})
  const [copied, setCopied] = useState(false)
  const [confirming, setConfirming] = useState(false)
  const [commitMsg, setCommitMsg] = useState(
    `fix: address ${findings.length} review finding${findings.length === 1 ? '' : 's'} (Round ${roundNumber})`,
  )

  const dialogRef = useRef<HTMLDivElement>(null)
  const navigate = useNavigate()
  const { socket } = useSocket()
  const { isRunning } = useCommandState()
  const { data: config } = useIdeConfig()
  const hasAiCli = !!config?.aiCli?.active
  const { commitStep, commitResult, commit, reset: resetCommit, diffStep, diffResult, requestDiff, sessionInfo, requestSessionInfo } = useFixFinding()

  // Fetch session info on mount so we know if this is a remote PR session
  useEffect(() => {
    requestSessionInfo(sessionId)
  }, [sessionId, requestSessionInfo])

  const isRemote = sessionInfo?.isRemote === true
  const isCollaborator = sessionInfo?.isCollaborator === true
  const remotePrCtx: RemotePrContext | undefined =
    isRemote && sessionInfo?.owner && sessionInfo?.repo && sessionInfo?.headRef
      ? {
          owner: sessionInfo.owner,
          repo: sessionInfo.repo,
          headRef: sessionInfo.headRef,
          isCollaborator,
          prNumber: sessionInfo.prNumber,
          prUrl: sessionInfo.prUrl,
        }
      : undefined

  const close = useCallback(() => {
    setConfirming(false)
    resetCommit()
    onClose()
  }, [onClose, resetCommit])

  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if (e.key === 'Escape') close()
    }
    document.addEventListener('keydown', handler)
    dialogRef.current?.focus()
    return () => document.removeEventListener('keydown', handler)
  }, [close])

  const prompt = buildBatchPrompt(findings, roundNumber, perNotes, globalNotes, remotePrCtx)

  function handleRunAgent() {
    const roundDir = `.ocr/sessions/${sessionId}/rounds/round-${roundNumber}`
    socket?.emit('command:run', {
      command: `ocr address ${roundDir}/final.md --requirements ${JSON.stringify(prompt)}`,
    })
    close()
    navigate('/commands')
  }

  async function handleCopy() {
    await navigator.clipboard.writeText(prompt)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  function handleCommit() {
    commit(commitMsg, sessionId)
  }

  function handleQueueReview() {
    const reviewCmd = isRemote && sessionInfo?.prUrl
      ? `ocr review ${sessionInfo.prUrl} --fresh`
      : 'ocr review'
    socket?.emit('command:run', { command: reviewCmd })
    close()
    navigate('/commands')
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      {/* backdrop */}
      <div className="fixed inset-0 bg-black/60" onClick={close} />
      <div
        ref={dialogRef}
        role="dialog"
        aria-modal="true"
        tabIndex={-1}
        className="relative z-10 flex w-full max-w-xl flex-col glass-card rounded-xl shadow-2xl focus:outline-none max-h-[90vh]"
      >
        {/* Header */}
        <div className="flex shrink-0 items-center justify-between border-b border-zinc-200 px-5 py-4 dark:border-white/[0.06]">
          <div>
            <h2 className="text-sm font-semibold text-zinc-900 dark:text-white">
              Batch Fix — {findings.length} finding{findings.length === 1 ? '' : 's'}
            </h2>
            <p className="mt-0.5 text-xs text-zinc-500 dark:text-zinc-400">
              One agent run · all findings fixed together
            </p>
          </div>
          <button
            onClick={close}
            className="ml-3 shrink-0 text-zinc-400 hover:text-zinc-600 dark:hover:text-zinc-300 cursor-pointer"
            aria-label="Close"
          >
            <X className="h-4 w-4" />
          </button>
        </div>

        {/* Tabs */}
        <div className="flex shrink-0 border-b border-zinc-200 dark:border-white/[0.06]">
          {(
            [
              { id: 'agent' as Tab, label: '1. Run Agent', icon: Wrench },
              { id: 'commit' as Tab, label: '2. Commit', icon: GitCommit },
              { id: 'review' as Tab, label: '3. Re-review', icon: RefreshCw },
            ] as const
          ).map(({ id, label, icon: Icon }) => (
            <button
              key={id}
              onClick={() => setTab(id)}
              className={cn(
                'flex flex-1 items-center justify-center gap-1.5 px-3 py-2.5 text-xs font-medium transition-colors cursor-pointer',
                tab === id
                  ? 'border-b-2 border-emerald-500 text-emerald-600 dark:text-emerald-400'
                  : 'text-zinc-500 hover:text-zinc-700 dark:text-zinc-400 dark:hover:text-zinc-200',
              )}
            >
              <Icon className="h-3 w-3" />
              {label}
            </button>
          ))}
        </div>

        {/* Scrollable body */}
        <div className="flex-1 overflow-y-auto p-5">
          {/* ── Tab 1: Run Agent ── */}
          {tab === 'agent' && (
            <div className="space-y-4">
              {/* Per-finding cards — notes always visible */}
              <div className="space-y-3">
                {findings.map((f, i) => (
                  <div
                    key={f.id}
                    className="rounded-lg border border-zinc-200 bg-zinc-50/60 dark:border-white/[0.06] dark:bg-white/[0.02]"
                  >
                    {/* Finding header */}
                    <div className="flex items-start gap-2 px-3 pt-3">
                      <span className="mt-0.5 shrink-0 font-mono text-[10px] text-zinc-400 dark:text-zinc-500">
                        {i + 1}.
                      </span>
                      <div className="min-w-0 flex-1">
                        <div className="flex flex-wrap items-center gap-1.5">
                          <span
                            className={cn(
                              'rounded px-1.5 py-0.5 text-[10px] font-semibold uppercase',
                              SEVERITY_CLS[f.severity] ?? SEVERITY_CLS.info,
                            )}
                          >
                            {f.severity}
                          </span>
                          <span className="text-xs font-medium text-zinc-800 dark:text-zinc-100">
                            {f.title}
                          </span>
                        </div>
                        {f.file_path && (
                          <p className="mt-0.5 font-mono text-[10px] text-zinc-400 dark:text-zinc-500">
                            {f.file_path}
                            {f.line_start != null ? `:${f.line_start}` : ''}
                          </p>
                        )}
                        {f.summary && (
                          <p className="mt-1 line-clamp-2 text-xs text-zinc-500 dark:text-zinc-400">
                            {f.summary}
                          </p>
                        )}
                      </div>
                    </div>

                    {/* Per-finding notes — always visible */}
                    <div className="px-3 pb-3 pt-2">
                      <textarea
                        value={perNotes[f.id] ?? ''}
                        onChange={(e) =>
                          setPerNotes((prev) => ({ ...prev, [f.id]: e.target.value }))
                        }
                        placeholder="Instructions for this finding only (optional) — e.g. use the helper in utils.ts, keep the same API signature…"
                        rows={2}
                        className="w-full resize-none rounded-md border border-zinc-200 bg-white px-2.5 py-1.5 text-xs placeholder:text-zinc-400 dark:border-white/[0.08] dark:bg-white/[0.04] dark:text-zinc-200 dark:placeholder:text-zinc-500 focus:outline-none focus:ring-1 focus:ring-emerald-500/50"
                      />
                    </div>
                  </div>
                ))}
              </div>

              {/* Global notes */}
              <div>
                <label className="text-xs font-medium text-zinc-500 dark:text-zinc-400">
                  Global context{' '}
                  <span className="font-normal text-zinc-400">(applies to all findings)</span>
                </label>
                <textarea
                  value={globalNotes}
                  onChange={(e) => setGlobalNotes(e.target.value)}
                  placeholder="e.g. Don't break the existing tests, use the helpers in utils.ts…"
                  rows={2}
                  className="mt-1 w-full resize-none rounded-md border border-zinc-200 bg-zinc-50 px-3 py-2 text-sm placeholder:text-zinc-400 dark:border-white/[0.08] dark:bg-white/[0.04] dark:text-zinc-200 dark:placeholder:text-zinc-500 focus:outline-none focus:ring-1 focus:ring-emerald-500/50"
                />
              </div>

              {hasAiCli ? (
                <>
                  {/* Loading state — wait for session info before allowing agent launch */}
                  {sessionInfo === null ? (
                    <div className="flex items-center gap-2 rounded-md border border-zinc-200 bg-zinc-50 px-3 py-2 text-xs text-zinc-500 dark:border-zinc-700 dark:bg-zinc-800 dark:text-zinc-400">
                      <Loader2 className="h-3.5 w-3.5 shrink-0 animate-spin" />
                      <span>Checking session type…</span>
                    </div>
                  ) : (
                    /* Show remote PR mode badge once session info is loaded */
                    isRemote ? (
                      <div className={cn(
                        'flex items-start gap-2 rounded-md border px-3 py-2 text-xs',
                        isCollaborator
                          ? 'border-emerald-200 bg-emerald-50 text-emerald-800 dark:border-emerald-900/50 dark:bg-emerald-950/30 dark:text-emerald-300'
                          : 'border-amber-200 bg-amber-50 text-amber-800 dark:border-amber-900/50 dark:bg-amber-950/30 dark:text-amber-300',
                      )}>
                        <ShieldAlert className="mt-0.5 h-3.5 w-3.5 shrink-0" />
                        <span>
                          {isCollaborator
                            ? `Collaborator access confirmed — agent will push fixes directly to \`${sessionInfo.headRef ?? 'PR branch'}\` on ${sessionInfo.owner}/${sessionInfo.repo}.`
                            : `Read-only access — you are not a collaborator on ${sessionInfo.owner}/${sessionInfo.repo}. Agent will post suggested fixes as a PR comment instead.`}
                        </span>
                      </div>
                    ) : (
                      <div className="flex items-start gap-2 rounded-md border border-amber-200 bg-amber-50 px-3 py-2 text-xs text-amber-800 dark:border-amber-900/50 dark:bg-amber-950/30 dark:text-amber-300">
                        <ShieldAlert className="mt-0.5 h-3.5 w-3.5 shrink-0" />
                        <span>
                          Runs a single AI agent with read/write access to fix all {findings.length}{' '}
                          finding{findings.length === 1 ? '' : 's'} in one pass. Review the diff before committing.
                        </span>
                      </div>
                    )
                  )}
                  <div className="flex gap-2">
                    {!confirming ? (
                      <button
                        onClick={() => setConfirming(true)}
                        disabled={isRunning || sessionInfo === null}
                        className={cn(
                          'flex flex-1 items-center justify-center gap-2 rounded-lg bg-emerald-600 px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-emerald-700 cursor-pointer',
                          (isRunning || sessionInfo === null) && 'cursor-not-allowed opacity-50',
                        )}
                      >
                        <Play className="h-3.5 w-3.5" />
                        Run Author Agent ({findings.length}{' '}
                        {findings.length === 1 ? 'fix' : 'fixes'})
                      </button>
                    ) : (
                      <button
                        onClick={handleRunAgent}
                        className="flex flex-1 items-center justify-center gap-2 rounded-lg bg-emerald-600 px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-emerald-700 cursor-pointer"
                      >
                        <Play className="h-3.5 w-3.5" />
                        Confirm — Start Agent
                      </button>
                    )}
                    <button
                      onClick={handleCopy}
                      title="Copy combined prompt to clipboard"
                      className="flex items-center justify-center gap-1.5 rounded-lg border border-zinc-200 px-3 py-2 text-sm font-medium text-zinc-600 transition-colors hover:bg-zinc-100 dark:border-white/[0.08] dark:text-zinc-300 dark:hover:bg-white/[0.05] cursor-pointer"
                    >
                      {copied ? (
                        <Check className="h-3.5 w-3.5" />
                      ) : (
                        <ClipboardCopy className="h-3.5 w-3.5" />
                      )}
                    </button>
                  </div>
                  <p className="text-center text-xs text-zinc-400 dark:text-zinc-500">
                    {isRemote
                      ? `Agent runs in Commands view — changes go directly to ${isCollaborator ? 'the PR branch' : 'a PR comment'}.`
                      : 'Agent runs in Commands view — come back here to commit when done.'}
                  </p>
                </>
              ) : (
                <div className="space-y-2">
                  <p className="text-xs text-zinc-500 dark:text-zinc-400">
                    Copy this combined prompt to your AI assistant:
                  </p>
                  <div className="max-h-40 overflow-y-auto rounded-md border border-zinc-200 bg-zinc-50 p-2.5 dark:border-white/[0.06] dark:bg-white/[0.03]">
                    <pre className="whitespace-pre-wrap font-mono text-[11px] text-zinc-600 dark:text-zinc-300">
                      {prompt}
                    </pre>
                  </div>
                  <button
                    onClick={handleCopy}
                    className="flex w-full items-center justify-center gap-2 rounded-lg bg-emerald-600 px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-emerald-700 cursor-pointer"
                  >
                    {copied ? (
                      <>
                        <Check className="h-3.5 w-3.5" />
                        Copied!
                      </>
                    ) : (
                      <>
                        <ClipboardCopy className="h-3.5 w-3.5" />
                        Copy Combined Prompt
                      </>
                    )}
                  </button>
                </div>
              )}
            </div>
          )}

          {/* ── Tab 2: Commit ── */}
          {tab === 'commit' && (
            <div className="space-y-4">
              {/* Remote PR mode: agent already pushed (collaborator) or commented (non-collaborator) */}
              {isRemote ? (
                <div className="space-y-3">
                  {isCollaborator ? (
                    <div className="rounded-lg border border-blue-200 bg-blue-50/60 px-4 py-3 text-xs text-blue-800 dark:border-blue-900/40 dark:bg-blue-950/30 dark:text-blue-300">
                      <p className="font-medium">Remote PR — no local commit needed</p>
                      <p className="mt-1 text-blue-700 dark:text-blue-400">
                        The Author Agent pushed changes directly to branch{' '}
                        <code className="font-mono">{sessionInfo?.headRef ?? 'PR branch'}</code> on{' '}
                        {sessionInfo?.owner}/{sessionInfo?.repo}. Nothing to commit locally.
                      </p>
                    </div>
                  ) : (
                    <div className="rounded-lg border border-amber-200 bg-amber-50/60 px-4 py-3 text-xs text-amber-800 dark:border-amber-900/40 dark:bg-amber-950/30 dark:text-amber-300">
                      <p className="font-medium">Read-only access — fix posted as PR comment</p>
                      <p className="mt-1 text-amber-700 dark:text-amber-400">
                        You are not a collaborator on{' '}
                        {sessionInfo?.owner}/{sessionInfo?.repo}. The Author Agent posted the
                        suggested fix as a comment on the PR for the maintainer to apply.
                      </p>
                    </div>
                  )}
                  {sessionInfo?.prUrl && (
                    <a
                      href={sessionInfo.prUrl}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="flex w-full items-center justify-center gap-2 rounded-lg border border-zinc-200 px-4 py-2.5 text-sm font-medium text-zinc-700 transition-colors hover:bg-zinc-50 dark:border-white/[0.08] dark:text-zinc-300 dark:hover:bg-white/[0.05] cursor-pointer"
                    >
                      <ExternalLink className="h-4 w-4" />
                      {isCollaborator ? 'Verify changes on GitHub' : 'View PR comment on GitHub'}
                    </a>
                  )}
                  {isCollaborator && (
                    <button
                      onClick={() => setTab('review')}
                      className="flex w-full items-center justify-center gap-2 rounded-lg bg-emerald-600 px-4 py-2.5 text-sm font-medium text-white transition-colors hover:bg-emerald-700 cursor-pointer"
                    >
                      <RefreshCw className="h-3.5 w-3.5" />
                      Next: Queue Re-review →
                    </button>
                  )}
                </div>
              ) : (
                <>
                  {/* Diff preview */}
                  <div>
                    <div className="flex items-center justify-between">
                      <span className="text-xs font-medium text-zinc-500 dark:text-zinc-400">
                        Changes from Author Agent
                      </span>
                      {diffStep !== 'loading' && (
                        <button
                          onClick={() => requestDiff(sessionId)}
                          className="inline-flex items-center gap-1 rounded px-2 py-0.5 text-xs font-medium text-zinc-500 hover:text-zinc-900 dark:text-zinc-400 dark:hover:text-zinc-100 cursor-pointer"
                        >
                          <Eye className="h-3 w-3" />
                          {diffStep === 'idle' ? 'Preview changes' : 'Refresh'}
                        </button>
                      )}
                    </div>

                    {diffStep === 'idle' && (
                      <div className="mt-1.5 flex items-center justify-center rounded-md border border-dashed border-zinc-300 py-6 dark:border-zinc-700">
                        <button
                          onClick={() => requestDiff(sessionId)}
                          className="inline-flex items-center gap-2 rounded-lg border border-zinc-200 px-4 py-2 text-sm font-medium text-zinc-600 transition-colors hover:bg-zinc-50 dark:border-white/[0.08] dark:text-zinc-300 dark:hover:bg-white/[0.05] cursor-pointer"
                        >
                          <Eye className="h-4 w-4" />
                          Preview changes before committing
                        </button>
                      </div>
                    )}

                    {diffStep === 'loading' && (
                      <div className="mt-1.5 flex items-center justify-center gap-2 rounded-md border border-zinc-200 py-6 text-sm text-zinc-500 dark:border-white/[0.06] dark:text-zinc-400">
                        <Loader2 className="h-4 w-4 animate-spin" />
                        Loading diff…
                      </div>
                    )}

                    {diffStep === 'ready' && diffResult && (
                      diffResult.empty ? (
                        <div className="mt-1.5 flex items-center justify-center rounded-md border border-amber-200 bg-amber-50 py-4 text-xs text-amber-700 dark:border-amber-900/50 dark:bg-amber-950/30 dark:text-amber-300">
                          No unstaged changes found. The agent may not have made any changes yet.
                        </div>
                      ) : (
                        <div className="mt-1.5 max-h-64 overflow-auto rounded-md border border-zinc-200 dark:border-white/[0.06]">
                          <DiffView diff={diffResult.diff} />
                        </div>
                      )
                    )}

                    {diffStep === 'error' && (
                      <div className="mt-1.5 rounded-md border border-red-500/25 bg-red-500/10 px-3 py-2 text-xs text-red-700 dark:text-red-400">
                        {diffResult?.error ?? 'Could not load diff.'}
                      </div>
                    )}
                  </div>

                  {/* Commit message */}
                  <div>
                    <label className="text-xs font-medium text-zinc-500 dark:text-zinc-400">
                      Commit message
                    </label>
                    <input
                      type="text"
                      value={commitMsg}
                      onChange={(e) => setCommitMsg(e.target.value)}
                      className="mt-1 w-full rounded-md border border-zinc-200 bg-zinc-50 px-3 py-2 text-sm dark:border-white/[0.08] dark:bg-white/[0.04] dark:text-zinc-200 focus:outline-none focus:ring-1 focus:ring-emerald-500/50"
                    />
                  </div>

                  {commitStep === 'idle' && (
                    <button
                      onClick={handleCommit}
                      disabled={!commitMsg.trim()}
                      className="flex w-full items-center justify-center gap-2 rounded-lg bg-emerald-600 px-4 py-2.5 text-sm font-medium text-white transition-colors hover:bg-emerald-700 disabled:cursor-not-allowed disabled:opacity-50 cursor-pointer"
                    >
                      <GitCommit className="h-4 w-4" />
                      Commit &amp; Push
                    </button>
                  )}

                  {commitStep === 'committing' && (
                    <div className="flex items-center justify-center gap-2 rounded-lg border border-zinc-200 py-3 text-sm text-zinc-500 dark:border-white/[0.06] dark:text-zinc-400">
                      <Loader2 className="h-4 w-4 animate-spin" />
                      Committing and pushing…
                    </div>
                  )}

                  {commitStep === 'done' && commitResult?.success && (
                    <div className="space-y-3">
                      <div className="flex items-center gap-2 rounded-lg border border-emerald-500/25 bg-emerald-500/10 px-4 py-3 text-sm text-emerald-700 dark:text-emerald-400">
                        <Check className="h-4 w-4 shrink-0" />
                        <span>
                          Committed <code className="font-mono">{commitResult.commitHash}</code> and
                          pushed.
                        </span>
                      </div>
                      <button
                        onClick={() => setTab('review')}
                        className="flex w-full items-center justify-center gap-2 rounded-lg border border-zinc-200 px-4 py-2 text-sm font-medium text-zinc-700 transition-colors hover:bg-zinc-50 dark:border-white/[0.08] dark:text-zinc-300 dark:hover:bg-white/[0.05] cursor-pointer"
                      >
                        <RefreshCw className="h-3.5 w-3.5" />
                        Next: Queue Re-review →
                      </button>
                    </div>
                  )}

                  {commitStep === 'error' && (
                    <div className="flex items-start gap-2 rounded-lg border border-red-500/25 bg-red-500/10 px-4 py-3 text-sm text-red-700 dark:text-red-400">
                      <AlertCircle className="mt-0.5 h-4 w-4 shrink-0" />
                      <span>
                        {commitResult?.error ??
                          'Commit failed. Check that the agent made changes first.'}
                      </span>
                    </div>
                  )}
                </>
              )}
            </div>
          )}

          {/* ── Tab 3: Re-review ── */}
          {tab === 'review' && (
            <div className="space-y-4">
              <div className="rounded-lg border border-zinc-200 bg-zinc-50 p-4 dark:border-white/[0.06] dark:bg-white/[0.03]">
                <h3 className="text-sm font-medium text-zinc-900 dark:text-zinc-100">
                  What happens next
                </h3>
                <ul className="mt-2 space-y-1.5 text-xs text-zinc-500 dark:text-zinc-400">
                  {[
                    `A new review round runs on the updated PR`,
                    `Reviewers check if all ${findings.length} finding${findings.length === 1 ? '' : 's'} were addressed`,
                    `Round ${roundNumber + 1} findings are compared against Round ${roundNumber}`,
                    'Resolved, still-open, and new findings are identified',
                  ].map((line) => (
                    <li key={line} className="flex items-start gap-1.5">
                      <span className="mt-0.5 h-1.5 w-1.5 shrink-0 rounded-full bg-emerald-500" />
                      {line}
                    </li>
                  ))}
                </ul>
              </div>
              <button
                onClick={handleQueueReview}
                disabled={isRunning}
                className={cn(
                  'flex w-full items-center justify-center gap-2 rounded-lg bg-emerald-600 px-4 py-2.5 text-sm font-medium text-white transition-colors hover:bg-emerald-700 cursor-pointer',
                  isRunning && 'cursor-not-allowed opacity-50',
                )}
              >
                <RefreshCw className="h-4 w-4" />
                Queue New Review Round
              </button>
              <p className="text-center text-xs text-zinc-400 dark:text-zinc-500">
                Runs <code className="font-mono">ocr review</code> in the Commands view.
              </p>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
